on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "**.py"
  workflow_dispatch: {}

jobs:
  test-go:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17.5
      - run: make coverage
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-python:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ^3.9.10
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          coverage run -m pytest
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
